package com.attitude.tinymall.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class LitemallPreDeliveryDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_pre_delivery_detail.delivery_id
     *
     * @mbg.generated
     */
    private String deliveryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_pre_delivery_detail.client_id
     *
     * @mbg.generated
     */
    private String clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_pre_delivery_detail.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_pre_delivery_detail.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_pre_delivery_detail.distance
     *
     * @mbg.generated
     */
    private String distance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_pre_delivery_detail.fee
     *
     * @mbg.generated
     */
    private Integer fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_pre_delivery_detail.deliver_fee
     *
     * @mbg.generated
     */
    private BigDecimal deliverFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_pre_delivery_detail.delivery_no
     *
     * @mbg.generated
     */
    private String deliveryNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_pre_delivery_detail.coupon_fee
     *
     * @mbg.generated
     */
    private BigDecimal couponFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_pre_delivery_detail.tips
     *
     * @mbg.generated
     */
    private BigDecimal tips;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_pre_delivery_detail.insurance_fee
     *
     * @mbg.generated
     */
    private BigDecimal insuranceFee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_pre_delivery_detail.delivery_id
     *
     * @return the value of tinymall_pre_delivery_detail.delivery_id
     *
     * @mbg.generated
     */
    public String getDeliveryId() {
        return deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_pre_delivery_detail.delivery_id
     *
     * @param deliveryId the value for tinymall_pre_delivery_detail.delivery_id
     *
     * @mbg.generated
     */
    public void setDeliveryId(String deliveryId) {
        this.deliveryId = deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_pre_delivery_detail.client_id
     *
     * @return the value of tinymall_pre_delivery_detail.client_id
     *
     * @mbg.generated
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_pre_delivery_detail.client_id
     *
     * @param clientId the value for tinymall_pre_delivery_detail.client_id
     *
     * @mbg.generated
     */
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_pre_delivery_detail.update_time
     *
     * @return the value of tinymall_pre_delivery_detail.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_pre_delivery_detail.update_time
     *
     * @param updateTime the value for tinymall_pre_delivery_detail.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_pre_delivery_detail.create_time
     *
     * @return the value of tinymall_pre_delivery_detail.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_pre_delivery_detail.create_time
     *
     * @param createTime the value for tinymall_pre_delivery_detail.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_pre_delivery_detail.distance
     *
     * @return the value of tinymall_pre_delivery_detail.distance
     *
     * @mbg.generated
     */
    public String getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_pre_delivery_detail.distance
     *
     * @param distance the value for tinymall_pre_delivery_detail.distance
     *
     * @mbg.generated
     */
    public void setDistance(String distance) {
        this.distance = distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_pre_delivery_detail.fee
     *
     * @return the value of tinymall_pre_delivery_detail.fee
     *
     * @mbg.generated
     */
    public Integer getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_pre_delivery_detail.fee
     *
     * @param fee the value for tinymall_pre_delivery_detail.fee
     *
     * @mbg.generated
     */
    public void setFee(Integer fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_pre_delivery_detail.deliver_fee
     *
     * @return the value of tinymall_pre_delivery_detail.deliver_fee
     *
     * @mbg.generated
     */
    public BigDecimal getDeliverFee() {
        return deliverFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_pre_delivery_detail.deliver_fee
     *
     * @param deliverFee the value for tinymall_pre_delivery_detail.deliver_fee
     *
     * @mbg.generated
     */
    public void setDeliverFee(BigDecimal deliverFee) {
        this.deliverFee = deliverFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_pre_delivery_detail.delivery_no
     *
     * @return the value of tinymall_pre_delivery_detail.delivery_no
     *
     * @mbg.generated
     */
    public String getDeliveryNo() {
        return deliveryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_pre_delivery_detail.delivery_no
     *
     * @param deliveryNo the value for tinymall_pre_delivery_detail.delivery_no
     *
     * @mbg.generated
     */
    public void setDeliveryNo(String deliveryNo) {
        this.deliveryNo = deliveryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_pre_delivery_detail.coupon_fee
     *
     * @return the value of tinymall_pre_delivery_detail.coupon_fee
     *
     * @mbg.generated
     */
    public BigDecimal getCouponFee() {
        return couponFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_pre_delivery_detail.coupon_fee
     *
     * @param couponFee the value for tinymall_pre_delivery_detail.coupon_fee
     *
     * @mbg.generated
     */
    public void setCouponFee(BigDecimal couponFee) {
        this.couponFee = couponFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_pre_delivery_detail.tips
     *
     * @return the value of tinymall_pre_delivery_detail.tips
     *
     * @mbg.generated
     */
    public BigDecimal getTips() {
        return tips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_pre_delivery_detail.tips
     *
     * @param tips the value for tinymall_pre_delivery_detail.tips
     *
     * @mbg.generated
     */
    public void setTips(BigDecimal tips) {
        this.tips = tips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_pre_delivery_detail.insurance_fee
     *
     * @return the value of tinymall_pre_delivery_detail.insurance_fee
     *
     * @mbg.generated
     */
    public BigDecimal getInsuranceFee() {
        return insuranceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_pre_delivery_detail.insurance_fee
     *
     * @param insuranceFee the value for tinymall_pre_delivery_detail.insurance_fee
     *
     * @mbg.generated
     */
    public void setInsuranceFee(BigDecimal insuranceFee) {
        this.insuranceFee = insuranceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_pre_delivery_detail
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", deliveryId=").append(deliveryId);
        sb.append(", clientId=").append(clientId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", distance=").append(distance);
        sb.append(", fee=").append(fee);
        sb.append(", deliverFee=").append(deliverFee);
        sb.append(", deliveryNo=").append(deliveryNo);
        sb.append(", couponFee=").append(couponFee);
        sb.append(", tips=").append(tips);
        sb.append(", insuranceFee=").append(insuranceFee);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_pre_delivery_detail
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallPreDeliveryDetail other = (LitemallPreDeliveryDetail) that;
        return (this.getDeliveryId() == null ? other.getDeliveryId() == null : this.getDeliveryId().equals(other.getDeliveryId()))
            && (this.getClientId() == null ? other.getClientId() == null : this.getClientId().equals(other.getClientId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getDistance() == null ? other.getDistance() == null : this.getDistance().equals(other.getDistance()))
            && (this.getFee() == null ? other.getFee() == null : this.getFee().equals(other.getFee()))
            && (this.getDeliverFee() == null ? other.getDeliverFee() == null : this.getDeliverFee().equals(other.getDeliverFee()))
            && (this.getDeliveryNo() == null ? other.getDeliveryNo() == null : this.getDeliveryNo().equals(other.getDeliveryNo()))
            && (this.getCouponFee() == null ? other.getCouponFee() == null : this.getCouponFee().equals(other.getCouponFee()))
            && (this.getTips() == null ? other.getTips() == null : this.getTips().equals(other.getTips()))
            && (this.getInsuranceFee() == null ? other.getInsuranceFee() == null : this.getInsuranceFee().equals(other.getInsuranceFee()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_pre_delivery_detail
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDeliveryId() == null) ? 0 : getDeliveryId().hashCode());
        result = prime * result + ((getClientId() == null) ? 0 : getClientId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getDistance() == null) ? 0 : getDistance().hashCode());
        result = prime * result + ((getFee() == null) ? 0 : getFee().hashCode());
        result = prime * result + ((getDeliverFee() == null) ? 0 : getDeliverFee().hashCode());
        result = prime * result + ((getDeliveryNo() == null) ? 0 : getDeliveryNo().hashCode());
        result = prime * result + ((getCouponFee() == null) ? 0 : getCouponFee().hashCode());
        result = prime * result + ((getTips() == null) ? 0 : getTips().hashCode());
        result = prime * result + ((getInsuranceFee() == null) ? 0 : getInsuranceFee().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table tinymall_pre_delivery_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        deliveryId("delivery_id", "deliveryId", "VARCHAR"),
        clientId("client_id", "clientId", "VARCHAR"),
        updateTime("update_time", "updateTime", "TIMESTAMP"),
        createTime("create_time", "createTime", "TIMESTAMP"),
        distance("distance", "distance", "VARCHAR"),
        fee("fee", "fee", "INTEGER"),
        deliverFee("deliver_fee", "deliverFee", "DECIMAL"),
        deliveryNo("delivery_no", "deliveryNo", "VARCHAR"),
        couponFee("coupon_fee", "couponFee", "DECIMAL"),
        tips("tips", "tips", "DECIMAL"),
        insuranceFee("insurance_fee", "insuranceFee", "DECIMAL");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tinymall_pre_delivery_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tinymall_pre_delivery_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tinymall_pre_delivery_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tinymall_pre_delivery_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tinymall_pre_delivery_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tinymall_pre_delivery_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tinymall_pre_delivery_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tinymall_pre_delivery_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tinymall_pre_delivery_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tinymall_pre_delivery_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}