package com.attitude.tinymall.domain;

import java.time.LocalDateTime;

public class LitemallDeliveryDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_delivery_detail.delivery_id
     *
     * @mbg.generated
     */
    private String deliveryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_delivery_detail.client_id
     *
     * @mbg.generated
     */
    private String clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_delivery_detail.dm_id
     *
     * @mbg.generated
     */
    private String dmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_delivery_detail.dm_name
     *
     * @mbg.generated
     */
    private String dmName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_delivery_detail.dm_mobile
     *
     * @mbg.generated
     */
    private String dmMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_delivery_detail.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_delivery_detail.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_delivery_detail.cancel_reason
     *
     * @mbg.generated
     */
    private String cancelReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_delivery_detail.cancel_from
     *
     * @mbg.generated
     */
    private String cancelFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_delivery_detail.distance
     *
     * @mbg.generated
     */
    private String distance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_delivery_detail.fee
     *
     * @mbg.generated
     */
    private Integer fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_delivery_detail.deliver_fee
     *
     * @mbg.generated
     */
    private Integer deliverFee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_delivery_detail.delivery_id
     *
     * @return the value of tinymall_delivery_detail.delivery_id
     *
     * @mbg.generated
     */
    public String getDeliveryId() {
        return deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_delivery_detail.delivery_id
     *
     * @param deliveryId the value for tinymall_delivery_detail.delivery_id
     *
     * @mbg.generated
     */
    public void setDeliveryId(String deliveryId) {
        this.deliveryId = deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_delivery_detail.client_id
     *
     * @return the value of tinymall_delivery_detail.client_id
     *
     * @mbg.generated
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_delivery_detail.client_id
     *
     * @param clientId the value for tinymall_delivery_detail.client_id
     *
     * @mbg.generated
     */
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_delivery_detail.dm_id
     *
     * @return the value of tinymall_delivery_detail.dm_id
     *
     * @mbg.generated
     */
    public String getDmId() {
        return dmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_delivery_detail.dm_id
     *
     * @param dmId the value for tinymall_delivery_detail.dm_id
     *
     * @mbg.generated
     */
    public void setDmId(String dmId) {
        this.dmId = dmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_delivery_detail.dm_name
     *
     * @return the value of tinymall_delivery_detail.dm_name
     *
     * @mbg.generated
     */
    public String getDmName() {
        return dmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_delivery_detail.dm_name
     *
     * @param dmName the value for tinymall_delivery_detail.dm_name
     *
     * @mbg.generated
     */
    public void setDmName(String dmName) {
        this.dmName = dmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_delivery_detail.dm_mobile
     *
     * @return the value of tinymall_delivery_detail.dm_mobile
     *
     * @mbg.generated
     */
    public String getDmMobile() {
        return dmMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_delivery_detail.dm_mobile
     *
     * @param dmMobile the value for tinymall_delivery_detail.dm_mobile
     *
     * @mbg.generated
     */
    public void setDmMobile(String dmMobile) {
        this.dmMobile = dmMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_delivery_detail.update_time
     *
     * @return the value of tinymall_delivery_detail.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_delivery_detail.update_time
     *
     * @param updateTime the value for tinymall_delivery_detail.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_delivery_detail.create_time
     *
     * @return the value of tinymall_delivery_detail.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_delivery_detail.create_time
     *
     * @param createTime the value for tinymall_delivery_detail.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_delivery_detail.cancel_reason
     *
     * @return the value of tinymall_delivery_detail.cancel_reason
     *
     * @mbg.generated
     */
    public String getCancelReason() {
        return cancelReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_delivery_detail.cancel_reason
     *
     * @param cancelReason the value for tinymall_delivery_detail.cancel_reason
     *
     * @mbg.generated
     */
    public void setCancelReason(String cancelReason) {
        this.cancelReason = cancelReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_delivery_detail.cancel_from
     *
     * @return the value of tinymall_delivery_detail.cancel_from
     *
     * @mbg.generated
     */
    public String getCancelFrom() {
        return cancelFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_delivery_detail.cancel_from
     *
     * @param cancelFrom the value for tinymall_delivery_detail.cancel_from
     *
     * @mbg.generated
     */
    public void setCancelFrom(String cancelFrom) {
        this.cancelFrom = cancelFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_delivery_detail.distance
     *
     * @return the value of tinymall_delivery_detail.distance
     *
     * @mbg.generated
     */
    public String getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_delivery_detail.distance
     *
     * @param distance the value for tinymall_delivery_detail.distance
     *
     * @mbg.generated
     */
    public void setDistance(String distance) {
        this.distance = distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_delivery_detail.fee
     *
     * @return the value of tinymall_delivery_detail.fee
     *
     * @mbg.generated
     */
    public Integer getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_delivery_detail.fee
     *
     * @param fee the value for tinymall_delivery_detail.fee
     *
     * @mbg.generated
     */
    public void setFee(Integer fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_delivery_detail.deliver_fee
     *
     * @return the value of tinymall_delivery_detail.deliver_fee
     *
     * @mbg.generated
     */
    public Integer getDeliverFee() {
        return deliverFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_delivery_detail.deliver_fee
     *
     * @param deliverFee the value for tinymall_delivery_detail.deliver_fee
     *
     * @mbg.generated
     */
    public void setDeliverFee(Integer deliverFee) {
        this.deliverFee = deliverFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_delivery_detail
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", deliveryId=").append(deliveryId);
        sb.append(", clientId=").append(clientId);
        sb.append(", dmId=").append(dmId);
        sb.append(", dmName=").append(dmName);
        sb.append(", dmMobile=").append(dmMobile);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", cancelReason=").append(cancelReason);
        sb.append(", cancelFrom=").append(cancelFrom);
        sb.append(", distance=").append(distance);
        sb.append(", fee=").append(fee);
        sb.append(", deliverFee=").append(deliverFee);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_delivery_detail
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallDeliveryDetail other = (LitemallDeliveryDetail) that;
        return (this.getDeliveryId() == null ? other.getDeliveryId() == null : this.getDeliveryId().equals(other.getDeliveryId()))
            && (this.getClientId() == null ? other.getClientId() == null : this.getClientId().equals(other.getClientId()))
            && (this.getDmId() == null ? other.getDmId() == null : this.getDmId().equals(other.getDmId()))
            && (this.getDmName() == null ? other.getDmName() == null : this.getDmName().equals(other.getDmName()))
            && (this.getDmMobile() == null ? other.getDmMobile() == null : this.getDmMobile().equals(other.getDmMobile()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCancelReason() == null ? other.getCancelReason() == null : this.getCancelReason().equals(other.getCancelReason()))
            && (this.getCancelFrom() == null ? other.getCancelFrom() == null : this.getCancelFrom().equals(other.getCancelFrom()))
            && (this.getDistance() == null ? other.getDistance() == null : this.getDistance().equals(other.getDistance()))
            && (this.getFee() == null ? other.getFee() == null : this.getFee().equals(other.getFee()))
            && (this.getDeliverFee() == null ? other.getDeliverFee() == null : this.getDeliverFee().equals(other.getDeliverFee()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_delivery_detail
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDeliveryId() == null) ? 0 : getDeliveryId().hashCode());
        result = prime * result + ((getClientId() == null) ? 0 : getClientId().hashCode());
        result = prime * result + ((getDmId() == null) ? 0 : getDmId().hashCode());
        result = prime * result + ((getDmName() == null) ? 0 : getDmName().hashCode());
        result = prime * result + ((getDmMobile() == null) ? 0 : getDmMobile().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCancelReason() == null) ? 0 : getCancelReason().hashCode());
        result = prime * result + ((getCancelFrom() == null) ? 0 : getCancelFrom().hashCode());
        result = prime * result + ((getDistance() == null) ? 0 : getDistance().hashCode());
        result = prime * result + ((getFee() == null) ? 0 : getFee().hashCode());
        result = prime * result + ((getDeliverFee() == null) ? 0 : getDeliverFee().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table tinymall_delivery_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        deliveryId("delivery_id", "deliveryId", "VARCHAR"),
        clientId("client_id", "clientId", "VARCHAR"),
        dmId("dm_id", "dmId", "VARCHAR"),
        dmName("dm_name", "dmName", "VARCHAR"),
        dmMobile("dm_mobile", "dmMobile", "VARCHAR"),
        updateTime("update_time", "updateTime", "TIMESTAMP"),
        createTime("create_time", "createTime", "TIMESTAMP"),
        cancelReason("cancel_reason", "cancelReason", "VARCHAR"),
        cancelFrom("cancel_from", "cancelFrom", "VARCHAR"),
        distance("distance", "distance", "VARCHAR"),
        fee("fee", "fee", "INTEGER"),
        deliverFee("deliver_fee", "deliverFee", "INTEGER");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tinymall_delivery_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tinymall_delivery_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tinymall_delivery_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tinymall_delivery_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tinymall_delivery_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tinymall_delivery_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tinymall_delivery_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tinymall_delivery_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tinymall_delivery_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tinymall_delivery_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}