package com.attitude.tinymall.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Objects;

public class LitemallOrder implements java.io.Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tinymall_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tinymall_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    @Deprecated
    public static final Boolean DEL_FLAG_ON = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tinymall_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean IS_DELETED = true;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tinymall_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    @Deprecated
    public static final Boolean DEL_FLAG_OFF = true;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.order_sn
     *
     * @mbg.generated
     */
    private String orderSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.order_status
     *
     * @mbg.generated
     */
    private Short orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.consignee
     *
     * @mbg.generated
     */
    private String consignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.goods_price
     *
     * @mbg.generated
     */
    private BigDecimal goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.freight_price
     *
     * @mbg.generated
     */
    private BigDecimal freightPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.coupon_price
     *
     * @mbg.generated
     */
    private BigDecimal couponPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.integral_price
     *
     * @mbg.generated
     */
    private BigDecimal integralPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.order_price
     *
     * @mbg.generated
     */
    private BigDecimal orderPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.actual_price
     *
     * @mbg.generated
     */
    private BigDecimal actualPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.pay_id
     *
     * @mbg.generated
     */
    private String payId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.pay_status
     *
     * @mbg.generated
     */
    private Short payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.pay_time
     *
     * @mbg.generated
     */
    private LocalDateTime payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.ship_sn
     *
     * @mbg.generated
     */
    private String shipSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.ship_channel
     *
     * @mbg.generated
     */
    private String shipChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.ship_start_time
     *
     * @mbg.generated
     */
    private LocalDateTime shipStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.ship_end_time
     *
     * @mbg.generated
     */
    private LocalDateTime shipEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.confirm_time
     *
     * @mbg.generated
     */
    private LocalDateTime confirmTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.end_time
     *
     * @mbg.generated
     */
    private LocalDateTime endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tinymall_order.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.id
     *
     * @return the value of tinymall_order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.id
     *
     * @param id the value for tinymall_order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.user_id
     *
     * @return the value of tinymall_order.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.user_id
     *
     * @param userId the value for tinymall_order.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.order_sn
     *
     * @return the value of tinymall_order.order_sn
     *
     * @mbg.generated
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.order_sn
     *
     * @param orderSn the value for tinymall_order.order_sn
     *
     * @mbg.generated
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.order_status
     *
     * @return the value of tinymall_order.order_status
     *
     * @mbg.generated
     */
    public Short getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.order_status
     *
     * @param orderStatus the value for tinymall_order.order_status
     *
     * @mbg.generated
     */
    public void setOrderStatus(Short orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.consignee
     *
     * @return the value of tinymall_order.consignee
     *
     * @mbg.generated
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.consignee
     *
     * @param consignee the value for tinymall_order.consignee
     *
     * @mbg.generated
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.mobile
     *
     * @return the value of tinymall_order.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.mobile
     *
     * @param mobile the value for tinymall_order.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.address
     *
     * @return the value of tinymall_order.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.address
     *
     * @param address the value for tinymall_order.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.goods_price
     *
     * @return the value of tinymall_order.goods_price
     *
     * @mbg.generated
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.goods_price
     *
     * @param goodsPrice the value for tinymall_order.goods_price
     *
     * @mbg.generated
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.freight_price
     *
     * @return the value of tinymall_order.freight_price
     *
     * @mbg.generated
     */
    public BigDecimal getFreightPrice() {
        return freightPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.freight_price
     *
     * @param freightPrice the value for tinymall_order.freight_price
     *
     * @mbg.generated
     */
    public void setFreightPrice(BigDecimal freightPrice) {
        this.freightPrice = freightPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.coupon_price
     *
     * @return the value of tinymall_order.coupon_price
     *
     * @mbg.generated
     */
    public BigDecimal getCouponPrice() {
        return couponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.coupon_price
     *
     * @param couponPrice the value for tinymall_order.coupon_price
     *
     * @mbg.generated
     */
    public void setCouponPrice(BigDecimal couponPrice) {
        this.couponPrice = couponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.integral_price
     *
     * @return the value of tinymall_order.integral_price
     *
     * @mbg.generated
     */
    public BigDecimal getIntegralPrice() {
        return integralPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.integral_price
     *
     * @param integralPrice the value for tinymall_order.integral_price
     *
     * @mbg.generated
     */
    public void setIntegralPrice(BigDecimal integralPrice) {
        this.integralPrice = integralPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.order_price
     *
     * @return the value of tinymall_order.order_price
     *
     * @mbg.generated
     */
    public BigDecimal getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.order_price
     *
     * @param orderPrice the value for tinymall_order.order_price
     *
     * @mbg.generated
     */
    public void setOrderPrice(BigDecimal orderPrice) {
        this.orderPrice = orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.actual_price
     *
     * @return the value of tinymall_order.actual_price
     *
     * @mbg.generated
     */
    public BigDecimal getActualPrice() {
        return actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.actual_price
     *
     * @param actualPrice the value for tinymall_order.actual_price
     *
     * @mbg.generated
     */
    public void setActualPrice(BigDecimal actualPrice) {
        this.actualPrice = actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.pay_id
     *
     * @return the value of tinymall_order.pay_id
     *
     * @mbg.generated
     */
    public String getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.pay_id
     *
     * @param payId the value for tinymall_order.pay_id
     *
     * @mbg.generated
     */
    public void setPayId(String payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.pay_status
     *
     * @return the value of tinymall_order.pay_status
     *
     * @mbg.generated
     */
    public Short getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.pay_status
     *
     * @param payStatus the value for tinymall_order.pay_status
     *
     * @mbg.generated
     */
    public void setPayStatus(Short payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.pay_time
     *
     * @return the value of tinymall_order.pay_time
     *
     * @mbg.generated
     */
    public LocalDateTime getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.pay_time
     *
     * @param payTime the value for tinymall_order.pay_time
     *
     * @mbg.generated
     */
    public void setPayTime(LocalDateTime payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.ship_sn
     *
     * @return the value of tinymall_order.ship_sn
     *
     * @mbg.generated
     */
    public String getShipSn() {
        return shipSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.ship_sn
     *
     * @param shipSn the value for tinymall_order.ship_sn
     *
     * @mbg.generated
     */
    public void setShipSn(String shipSn) {
        this.shipSn = shipSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.ship_channel
     *
     * @return the value of tinymall_order.ship_channel
     *
     * @mbg.generated
     */
    public String getShipChannel() {
        return shipChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.ship_channel
     *
     * @param shipChannel the value for tinymall_order.ship_channel
     *
     * @mbg.generated
     */
    public void setShipChannel(String shipChannel) {
        this.shipChannel = shipChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.ship_start_time
     *
     * @return the value of tinymall_order.ship_start_time
     *
     * @mbg.generated
     */
    public LocalDateTime getShipStartTime() {
        return shipStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.ship_start_time
     *
     * @param shipStartTime the value for tinymall_order.ship_start_time
     *
     * @mbg.generated
     */
    public void setShipStartTime(LocalDateTime shipStartTime) {
        this.shipStartTime = shipStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.ship_end_time
     *
     * @return the value of tinymall_order.ship_end_time
     *
     * @mbg.generated
     */
    public LocalDateTime getShipEndTime() {
        return shipEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.ship_end_time
     *
     * @param shipEndTime the value for tinymall_order.ship_end_time
     *
     * @mbg.generated
     */
    public void setShipEndTime(LocalDateTime shipEndTime) {
        this.shipEndTime = shipEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.confirm_time
     *
     * @return the value of tinymall_order.confirm_time
     *
     * @mbg.generated
     */
    public LocalDateTime getConfirmTime() {
        return confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.confirm_time
     *
     * @param confirmTime the value for tinymall_order.confirm_time
     *
     * @mbg.generated
     */
    public void setConfirmTime(LocalDateTime confirmTime) {
        this.confirmTime = confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.end_time
     *
     * @return the value of tinymall_order.end_time
     *
     * @mbg.generated
     */
    public LocalDateTime getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.end_time
     *
     * @param endTime the value for tinymall_order.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.add_time
     *
     * @return the value of tinymall_order.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.add_time
     *
     * @param addTime the value for tinymall_order.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * tinymall_order
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        return "LitemallOrder{" +
            "id=" + id +
            ", userId=" + userId +
            ", orderSn='" + orderSn + '\'' +
            ", orderStatus=" + orderStatus +
            ", consignee='" + consignee + '\'' +
            ", mobile='" + mobile + '\'' +
            ", address='" + address + '\'' +
            ", goodsPrice=" + goodsPrice +
            ", freightPrice=" + freightPrice +
            ", couponPrice=" + couponPrice +
            ", integralPrice=" + integralPrice +
            ", orderPrice=" + orderPrice +
            ", actualPrice=" + actualPrice +
            ", payId='" + payId + '\'' +
            ", payStatus=" + payStatus +
            ", payTime=" + payTime +
            ", shipSn='" + shipSn + '\'' +
            ", shipChannel='" + shipChannel + '\'' +
            ", shipStartTime=" + shipStartTime +
            ", shipEndTime=" + shipEndTime +
            ", confirmTime=" + confirmTime +
            ", endTime=" + endTime +
            ", addTime=" + addTime +
            ", adminId=" + adminId +
            ", deleted=" + deleted +
            '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        LitemallOrder that = (LitemallOrder) o;
        return Objects.equals(id, that.id) &&
            Objects.equals(userId, that.userId) &&
            Objects.equals(orderSn, that.orderSn) &&
            Objects.equals(orderStatus, that.orderStatus) &&
            Objects.equals(consignee, that.consignee) &&
            Objects.equals(mobile, that.mobile) &&
            Objects.equals(address, that.address) &&
            Objects.equals(goodsPrice, that.goodsPrice) &&
            Objects.equals(freightPrice, that.freightPrice) &&
            Objects.equals(couponPrice, that.couponPrice) &&
            Objects.equals(integralPrice, that.integralPrice) &&
            Objects.equals(orderPrice, that.orderPrice) &&
            Objects.equals(actualPrice, that.actualPrice) &&
            Objects.equals(payId, that.payId) &&
            Objects.equals(payStatus, that.payStatus) &&
            Objects.equals(payTime, that.payTime) &&
            Objects.equals(shipSn, that.shipSn) &&
            Objects.equals(shipChannel, that.shipChannel) &&
            Objects.equals(shipStartTime, that.shipStartTime) &&
            Objects.equals(shipEndTime, that.shipEndTime) &&
            Objects.equals(confirmTime, that.confirmTime) &&
            Objects.equals(endTime, that.endTime) &&
            Objects.equals(addTime, that.addTime) &&
            Objects.equals(adminId, that.adminId) &&
            Objects.equals(deleted, that.deleted);
    }

    @Override
    public int hashCode() {
        return Objects
            .hash(id, userId, orderSn, orderStatus, consignee, mobile, address, goodsPrice,
                freightPrice,
                couponPrice, integralPrice, orderPrice, actualPrice, payId, payStatus, payTime,
                shipSn,
                shipChannel, shipStartTime, shipEndTime, confirmTime, endTime, addTime, adminId,
                deleted);
    }

    public Integer getAdminId() {
        return adminId;
    }

    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tinymall_order.deleted
     *
     * @return the value of tinymall_order.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tinymall_order.deleted
     *
     * @param deleted the value for tinymall_order.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tinymall_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? IS_DELETED : NOT_DELETED);
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table tinymall_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER"),
        userId("user_id", "userId", "INTEGER"),
        orderSn("order_sn", "orderSn", "VARCHAR"),
        orderStatus("order_status", "orderStatus", "SMALLINT"),
        consignee("consignee", "consignee", "VARCHAR"),
        mobile("mobile", "mobile", "VARCHAR"),
        address("address", "address", "VARCHAR"),
        goodsPrice("goods_price", "goodsPrice", "DECIMAL"),
        freightPrice("freight_price", "freightPrice", "DECIMAL"),
        couponPrice("coupon_price", "couponPrice", "DECIMAL"),
        integralPrice("integral_price", "integralPrice", "DECIMAL"),
        orderPrice("order_price", "orderPrice", "DECIMAL"),
        actualPrice("actual_price", "actualPrice", "DECIMAL"),
        payId("pay_id", "payId", "VARCHAR"),
        payStatus("pay_status", "payStatus", "SMALLINT"),
        payTime("pay_time", "payTime", "TIMESTAMP"),
        shipSn("ship_sn", "shipSn", "VARCHAR"),
        shipChannel("ship_channel", "shipChannel", "VARCHAR"),
        shipStartTime("ship_start_time", "shipStartTime", "TIMESTAMP"),
        shipEndTime("ship_end_time", "shipEndTime", "TIMESTAMP"),
        confirmTime("confirm_time", "confirmTime", "TIMESTAMP"),
        endTime("end_time", "endTime", "TIMESTAMP"),
        addTime("add_time", "addTime", "TIMESTAMP"),
        deleted("deleted", "deleted", "BIT"),
        adminId("admin_id", "adminId", "VARCHAR");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tinymall_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tinymall_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tinymall_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tinymall_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tinymall_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tinymall_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tinymall_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tinymall_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tinymall_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tinymall_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}