package com.attitude.tinymall.db.domain;

import java.time.LocalDateTime;

public class LitemallAdmin {

  public static final int USER_LIMIT = 1000000;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * tinymall_admin
   *
   * @mbg.generated
   * @project https://github.com/itfsw/mybatis-generator-plugin
   */
  public static final Boolean NOT_DELETED = false;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * tinymall_admin
   *
   * @mbg.generated
   * @project https://github.com/itfsw/mybatis-generator-plugin
   */
  @Deprecated
  public static final Boolean DEL_FLAG_ON = false;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * tinymall_admin
   *
   * @mbg.generated
   * @project https://github.com/itfsw/mybatis-generator-plugin
   */
  public static final Boolean IS_DELETED = true;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * tinymall_admin
   *
   * @mbg.generated
   * @project https://github.com/itfsw/mybatis-generator-plugin
   */
  @Deprecated
  public static final Boolean DEL_FLAG_OFF = true;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tinymall_admin.id
   *
   * @mbg.generated
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tinymall_admin.username
   *
   * @mbg.generated
   */
  private String username;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tinymall_admin.password
   *
   * @mbg.generated
   */
  private String password;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tinymall_admin.last_login_ip
   *
   * @mbg.generated
   */
  private String lastLoginIp;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tinymall_admin.last_login_time
   *
   * @mbg.generated
   */
  private LocalDateTime lastLoginTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tinymall_admin.update_time
   *
   * @mbg.generated
   */
  private LocalDateTime updateTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tinymall_admin.avatar
   *
   * @mbg.generated
   */
  private String avatar;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tinymall_admin.add_time
   *
   * @mbg.generated
   */
  private LocalDateTime addTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tinymall_admin.deleted
   *
   * @mbg.generated
   */
  private Boolean deleted;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tinymall_admin.owner_id
   *
   * @mbg.generated
   */
  private String ownerId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tinymall_admin.app_secret
   *
   * @mbg.generated
   */
  private String appSecret;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tinymall_admin.mch_id
   *
   * @mbg.generated
   */
  private Integer mchId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tinymall_admin.mch_key
   *
   * @mbg.generated
   */
  private String mchKey;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tinymall_admin.notify_url
   *
   * @mbg.generated
   */
  private String notifyUrl;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tinymall_admin.shop_name
   *
   * @mbg.generated
   */
  private String shopName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tinymall_admin.shop_address
   *
   * @mbg.generated
   */
  private String shopAddress;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tinymall_admin.shop_fence_id
   *
   * @mbg.generated
   */
  private Integer shopFenceId;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tinymall_admin.id
   *
   * @return the value of tinymall_admin.id
   * @mbg.generated
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tinymall_admin.id
   *
   * @param id the value for tinymall_admin.id
   * @mbg.generated
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tinymall_admin.username
   *
   * @return the value of tinymall_admin.username
   * @mbg.generated
   */
  public String getUsername() {
    return username;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tinymall_admin.username
   *
   * @param username the value for tinymall_admin.username
   * @mbg.generated
   */
  public void setUsername(String username) {
    this.username = username;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tinymall_admin.password
   *
   * @return the value of tinymall_admin.password
   * @mbg.generated
   */
  public String getPassword() {
    return password;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tinymall_admin.password
   *
   * @param password the value for tinymall_admin.password
   * @mbg.generated
   */
  public void setPassword(String password) {
    this.password = password;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tinymall_admin.last_login_ip
   *
   * @return the value of tinymall_admin.last_login_ip
   * @mbg.generated
   */
  public String getLastLoginIp() {
    return lastLoginIp;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tinymall_admin.last_login_ip
   *
   * @param lastLoginIp the value for tinymall_admin.last_login_ip
   * @mbg.generated
   */
  public void setLastLoginIp(String lastLoginIp) {
    this.lastLoginIp = lastLoginIp;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tinymall_admin.last_login_time
   *
   * @return the value of tinymall_admin.last_login_time
   * @mbg.generated
   */
  public LocalDateTime getLastLoginTime() {
    return lastLoginTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tinymall_admin.last_login_time
   *
   * @param lastLoginTime the value for tinymall_admin.last_login_time
   * @mbg.generated
   */
  public void setLastLoginTime(LocalDateTime lastLoginTime) {
    this.lastLoginTime = lastLoginTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tinymall_admin.update_time
   *
   * @return the value of tinymall_admin.update_time
   * @mbg.generated
   */
  public LocalDateTime getUpdateTime() {
    return updateTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tinymall_admin.update_time
   *
   * @param updateTime the value for tinymall_admin.update_time
   * @mbg.generated
   */
  public void setUpdateTime(LocalDateTime updateTime) {
    this.updateTime = updateTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tinymall_admin.avatar
   *
   * @return the value of tinymall_admin.avatar
   * @mbg.generated
   */
  public String getAvatar() {
    return avatar;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tinymall_admin.avatar
   *
   * @param avatar the value for tinymall_admin.avatar
   * @mbg.generated
   */
  public void setAvatar(String avatar) {
    this.avatar = avatar;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tinymall_admin.add_time
   *
   * @return the value of tinymall_admin.add_time
   * @mbg.generated
   */
  public LocalDateTime getAddTime() {
    return addTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tinymall_admin.add_time
   *
   * @param addTime the value for tinymall_admin.add_time
   * @mbg.generated
   */
  public void setAddTime(LocalDateTime addTime) {
    this.addTime = addTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tinymall_admin.deleted
   *
   * @return the value of tinymall_admin.deleted
   * @mbg.generated
   */
  public Boolean getDeleted() {
    return deleted;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tinymall_admin.deleted
   *
   * @param deleted the value for tinymall_admin.deleted
   * @mbg.generated
   */
  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tinymall_admin.owner_id
   *
   * @return the value of tinymall_admin.owner_id
   * @mbg.generated
   */
  public String getOwnerId() {
    return ownerId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tinymall_admin.owner_id
   *
   * @param ownerId the value for tinymall_admin.owner_id
   * @mbg.generated
   */
  public void setOwnerId(String ownerId) {
    this.ownerId = ownerId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tinymall_admin.app_secret
   *
   * @return the value of tinymall_admin.app_secret
   * @mbg.generated
   */
  public String getAppSecret() {
    return appSecret;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tinymall_admin.app_secret
   *
   * @param appSecret the value for tinymall_admin.app_secret
   * @mbg.generated
   */
  public void setAppSecret(String appSecret) {
    this.appSecret = appSecret;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tinymall_admin.mch_id
   *
   * @return the value of tinymall_admin.mch_id
   * @mbg.generated
   */
  public Integer getMchId() {
    return mchId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tinymall_admin.mch_id
   *
   * @param mchId the value for tinymall_admin.mch_id
   * @mbg.generated
   */
  public void setMchId(Integer mchId) {
    this.mchId = mchId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tinymall_admin.mch_key
   *
   * @return the value of tinymall_admin.mch_key
   * @mbg.generated
   */
  public String getMchKey() {
    return mchKey;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tinymall_admin.mch_key
   *
   * @param mchKey the value for tinymall_admin.mch_key
   * @mbg.generated
   */
  public void setMchKey(String mchKey) {
    this.mchKey = mchKey;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tinymall_admin.notify_url
   *
   * @return the value of tinymall_admin.notify_url
   * @mbg.generated
   */
  public String getNotifyUrl() {
    return notifyUrl;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tinymall_admin.notify_url
   *
   * @param notifyUrl the value for tinymall_admin.notify_url
   * @mbg.generated
   */
  public void setNotifyUrl(String notifyUrl) {
    this.notifyUrl = notifyUrl;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tinymall_admin.shop_name
   *
   * @return the value of tinymall_admin.shop_name
   * @mbg.generated
   */
  public String getShopName() {
    return shopName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tinymall_admin.shop_name
   *
   * @param shopName the value for tinymall_admin.shop_name
   * @mbg.generated
   */
  public void setShopName(String shopName) {
    this.shopName = shopName;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tinymall_admin.shop_address
   *
   * @return the value of tinymall_admin.shop_address
   * @mbg.generated
   */
  public String getShopAddress() {
    return shopAddress;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tinymall_admin.shop_address
   *
   * @param shopAddress the value for tinymall_admin.shop_address
   * @mbg.generated
   */
  public void setShopAddress(String shopAddress) {
    this.shopAddress = shopAddress;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column tinymall_admin.shop_fence_id
   *
   * @return the value of tinymall_admin.shop_fence_id
   * @mbg.generated
   */
  public Integer getShopFenceId() {
    return shopFenceId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column tinymall_admin.shop_fence_id
   *
   * @param shopFenceId the value for tinymall_admin.shop_fence_id
   * @mbg.generated
   */
  public void setShopFenceId(Integer shopFenceId) {
    this.shopFenceId = shopFenceId;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tinymall_admin
   *
   * @mbg.generated
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append(getClass().getSimpleName());
    sb.append(" [");
    sb.append("Hash = ").append(hashCode());
    sb.append(", id=").append(id);
    sb.append(", username=").append(username);
    sb.append(", password=").append(password);
    sb.append(", lastLoginIp=").append(lastLoginIp);
    sb.append(", lastLoginTime=").append(lastLoginTime);
    sb.append(", updateTime=").append(updateTime);
    sb.append(", avatar=").append(avatar);
    sb.append(", addTime=").append(addTime);
    sb.append(", deleted=").append(deleted);
    sb.append(", ownerId=").append(ownerId);
    sb.append(", appSecret=").append(appSecret);
    sb.append(", mchId=").append(mchId);
    sb.append(", mchKey=").append(mchKey);
    sb.append(", notifyUrl=").append(notifyUrl);
    sb.append(", shopName=").append(shopName);
    sb.append(", shopAddress=").append(shopAddress);
    sb.append(", shopFenceId=").append(shopFenceId);
    sb.append("]");
    return sb.toString();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tinymall_admin
   *
   * @mbg.generated
   */
  @Override
  public boolean equals(Object that) {
    if (this == that) {
      return true;
    }
    if (that == null) {
      return false;
    }
    if (getClass() != that.getClass()) {
      return false;
    }
    LitemallAdmin other = (LitemallAdmin) that;
    return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        && (this.getUsername() == null ? other.getUsername() == null
        : this.getUsername().equals(other.getUsername()))
        && (this.getPassword() == null ? other.getPassword() == null
        : this.getPassword().equals(other.getPassword()))
        && (this.getLastLoginIp() == null ? other.getLastLoginIp() == null
        : this.getLastLoginIp().equals(other.getLastLoginIp()))
        && (this.getLastLoginTime() == null ? other.getLastLoginTime() == null
        : this.getLastLoginTime().equals(other.getLastLoginTime()))
        && (this.getUpdateTime() == null ? other.getUpdateTime() == null
        : this.getUpdateTime().equals(other.getUpdateTime()))
        && (this.getAvatar() == null ? other.getAvatar() == null
        : this.getAvatar().equals(other.getAvatar()))
        && (this.getAddTime() == null ? other.getAddTime() == null
        : this.getAddTime().equals(other.getAddTime()))
        && (this.getDeleted() == null ? other.getDeleted() == null
        : this.getDeleted().equals(other.getDeleted()))
        && (this.getOwnerId() == null ? other.getOwnerId() == null
        : this.getOwnerId().equals(other.getOwnerId()))
        && (this.getAppSecret() == null ? other.getAppSecret() == null
        : this.getAppSecret().equals(other.getAppSecret()))
        && (this.getMchId() == null ? other.getMchId() == null
        : this.getMchId().equals(other.getMchId()))
        && (this.getMchKey() == null ? other.getMchKey() == null
        : this.getMchKey().equals(other.getMchKey()))
        && (this.getNotifyUrl() == null ? other.getNotifyUrl() == null
        : this.getNotifyUrl().equals(other.getNotifyUrl()))
        && (this.getShopName() == null ? other.getShopName() == null
        : this.getShopName().equals(other.getShopName()))
        && (this.getShopAddress() == null ? other.getShopAddress() == null
        : this.getShopAddress().equals(other.getShopAddress()))
        && (this.getShopFenceId() == null ? other.getShopFenceId() == null
        : this.getShopFenceId().equals(other.getShopFenceId()));
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tinymall_admin
   *
   * @mbg.generated
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
    result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
    result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
    result = prime * result + ((getLastLoginIp() == null) ? 0 : getLastLoginIp().hashCode());
    result = prime * result + ((getLastLoginTime() == null) ? 0 : getLastLoginTime().hashCode());
    result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
    result = prime * result + ((getAvatar() == null) ? 0 : getAvatar().hashCode());
    result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
    result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
    result = prime * result + ((getOwnerId() == null) ? 0 : getOwnerId().hashCode());
    result = prime * result + ((getAppSecret() == null) ? 0 : getAppSecret().hashCode());
    result = prime * result + ((getMchId() == null) ? 0 : getMchId().hashCode());
    result = prime * result + ((getMchKey() == null) ? 0 : getMchKey().hashCode());
    result = prime * result + ((getNotifyUrl() == null) ? 0 : getNotifyUrl().hashCode());
    result = prime * result + ((getShopName() == null) ? 0 : getShopName().hashCode());
    result = prime * result + ((getShopAddress() == null) ? 0 : getShopAddress().hashCode());
    result = prime * result + ((getShopFenceId() == null) ? 0 : getShopFenceId().hashCode());
    return result;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * tinymall_admin
   *
   * @mbg.generated
   * @project https://github.com/itfsw/mybatis-generator-plugin
   */
  public void andLogicalDeleted(boolean deleted) {
    setDeleted(deleted ? IS_DELETED : NOT_DELETED);
  }

  /**
   * This enum was generated by MyBatis Generator. This enum corresponds to the database table
   * tinymall_admin
   *
   * @mbg.generated
   * @project https://github.com/itfsw/mybatis-generator-plugin
   */
  public enum Column {
    id("id", "id", "INTEGER"),
    username("username", "username", "VARCHAR"),
    password("password", "password", "VARCHAR"),
    lastLoginIp("last_login_ip", "lastLoginIp", "VARCHAR"),
    lastLoginTime("last_login_time", "lastLoginTime", "TIMESTAMP"),
    updateTime("update_time", "updateTime", "TIMESTAMP"),
    avatar("avatar", "avatar", "VARCHAR"),
    addTime("add_time", "addTime", "TIMESTAMP"),
    deleted("deleted", "deleted", "BIT"),
    ownerId("owner_id", "ownerId", "VARCHAR"),
    appSecret("app_secret", "appSecret", "VARCHAR"),
    mchId("mch_id", "mchId", "INTEGER"),
    mchKey("mch_key", "mchKey", "VARCHAR"),
    notifyUrl("notify_url", "notifyUrl", "VARCHAR"),
    shopName("shop_name", "shopName", "VARCHAR"),
    shopAddress("shop_address", "shopAddress", "VARCHAR"),
    shopFenceId("shop_fence_id", "shopFenceId", "INTEGER");

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * tinymall_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private final String column;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * tinymall_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private final String javaProperty;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * tinymall_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private final String jdbcType;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * tinymall_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public String value() {
      return this.column;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * tinymall_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public String getValue() {
      return this.column;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * tinymall_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public String getJavaProperty() {
      return this.javaProperty;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * tinymall_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public String getJdbcType() {
      return this.jdbcType;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * tinymall_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Column(String column, String javaProperty, String jdbcType) {
      this.column = column;
      this.javaProperty = javaProperty;
      this.jdbcType = jdbcType;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * tinymall_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public String desc() {
      return this.column + " DESC";
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * tinymall_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public String asc() {
      return this.column + " ASC";
    }
  }
}
